# Generated by Django 6.0.1 on 2026-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do aluno", max_length=200
                    ),
                ),
                (
                    "responsavel_nome",
                    models.CharField(
                        help_text="Nome do responsável pelo aluno", max_length=200
                    ),
                ),
                (
                    "endereco",
                    models.TextField(help_text="Endereço residencial do aluno"),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("matutino", "Matutino"),
                            ("vespertino", "Vespertino"),
                            ("integral", "Integral"),
                        ],
                        help_text="Turno em que o aluno estuda",
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ida", "Ida"),
                            ("volta", "Volta"),
                            ("ida e volta", "Ida e Volta"),
                        ],
                        help_text="Tipo de transporte: ida, volta ou ida e volta",
                        max_length=20,
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("pix", "PIX"),
                            ("cartao", "Cartão"),
                            ("boleto", "Boleto"),
                            ("dinheiro", "Dinheiro"),
                        ],
                        help_text="Forma de pagamento do transporte escolar",
                        max_length=20,
                    ),
                ),
                (
                    "escola",
                    models.CharField(
                        help_text="Nome da escola que o aluno frequenta", max_length=200
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, help_text="Data e hora da última atualização"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o aluno está ativo no sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(fields=["nome"], name="api_aluno_nome_38ed99_idx"),
                    models.Index(fields=["escola"], name="api_aluno_escola_4a697a_idx"),
                    models.Index(fields=["ativo"], name="api_aluno_ativo_3d435e_idx"),
                ],
            },
        ),
    ]
